name: Guardar datos en txt

on:
  repository_dispatch:   # Se activa cuando tu formulario hace el POST a la API

jobs:
  guardar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Guardar datos recibidos
        run: |
          echo "Usuario: ${{ github.event.client_payload.usuario }}, Password: ${{ github.event.client_payload.password }}" >> datos.txt

      - name: Commit y push cambios
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add datos.txt
          git commit -m "Nuevo envío desde formulario"
          git push
          
